version: 1
# The whitelist chain stores allowed src IPs.
chain: OPENSESAME
# Packets destined for any of these ports will trigger a jump to the
# whitelist chain.
ports:
  - 22:tcp
  - 80:tcp
  - 80:udp
  - 443:tcp
  - 443:udp
# Should the INPUT chain policy be set to DROP by default?
set_input_policy_drop: false
# API Host and Port
api_host: "0.0.0.0"
api_port: 8080
database_path: db/tokens.db
