services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8080:8080
  test:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.test
    cap_add:
      - NET_ADMIN
      - NET_RAW
