[tool.ruff]
line-length = 90

lint.select = ["E", "F"]

fix = true
lint.unfixable = ["F401"] # unused imports

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
