[tool.ruff]
line-length = 90

lint.select = ["E", "F"]

fix = true
lint.unfixable = ["F401"] # unused imports

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"


[tool.bumpver]
current_version = "0.4.3"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} → {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"']
"setup.py" = ["version='{version}'"]
