FROM python:3.11.8-slim AS base
RUN apt-get update && apt-get -y install iptables

FROM base AS test
RUN apt-get -y install gcc

ENV PYTHONUNBUFFERED=1
# https://github.com/ldx/python-iptables/issues/37
# ENV XTABLES_LIBDIR=/usr/lib/iptables

WORKDIR /opt/app
COPY requirements.test.txt /opt/app/

RUN pip install -r requirements.test.txt

COPY . /opt/app

RUN pip install --no-cache-dir -e .[tests]
RUN mkdir /db

CMD pytest -svv
