FROM python:3.8.1-slim

RUN apt-get update && apt-get -y install gcc iptables

COPY . /app
WORKDIR /app

ARG PIP_INS="pip install --no-cache-dir"

RUN $PIP_INS -r requirements.txt -r requirements.test.txt -e .

CMD pytest -svv
