FROM python:3.8.1-slim

RUN apt-get update && apt-get -y install gcc iptables

COPY . /app
WORKDIR /app

ARG PIP_INS="pip install --no-cache-dir"

RUN $PIP_INS -r requirements.txt && \
    $PIP_INS -r requirements-dev.txt && \
    $PIP_INS -e .

CMD pytest -svv
