name: Run tests with Docker

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:

jobs:
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  run_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker-compose build test
          docker-compose run test
